baseurl: "/"
languageCode: "en-us"
title: "A minimal Hugo website"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "â†©"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

#menu:
  #main:
  #  - name: Home
  #    url: ""
  #    weight: 1
  #  - name: About
  #    url: "about/"
  #    weight: 2

params:
  description: "A website built through Hugo and blogdown."
  footer: "[Google Scholar](https://scholar.google.com/citations?user=ha8hFp8AAAAJ) | [LinkedIn](https://www.linkedin.com/in/florianpethig/) | [Twitter](https://twitter.com/florianpethig) | Layout based on [&copy; 2017--{Year} Yihui Xie](https://github.com/yihui/hugo-xmin)"
markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
